### ISSUE TITLE
[4.0.0-beta2][ES]ES always going back to the root of the system folder after exiting a game (instead of last game used)

### ISSUE THREAD

**Issue by bigboo3000** [recalbox/recalbox-os#831] opened 2016-03-22 13:22 UTC
When you have multiple folders in a system, ES always goes back to the root when you quit a game,  instead of goes back to the last game used.
Is it possible to change that. (go back to the last game used, like it is doing when there are no multiple folders)

**Comment by Voljega** [comment] 2016-03-22 15:20
duplicate of https://github.com/recalbox/recalbox-os/issues/742 ;)

**Comment by substring** [comment] 2016-03-22 15:22
Was too lazy to look for it lol

**Closed by substring** 2016-03-22 15:22 UTC
