### ISSUE TITLE
SSh use locks terminal

### ISSUE THREAD

**Issue by josecarlosbarros** [recalbox/recalbox-os#1189] opened 2017-02-04 14:59 UTC
### Before posting issue 
- For support go to **IRC** or **forum**. Github is only for development issue/improvement 
- Be sure your issue is not already reported : check https://github.com/recalbox/recalbox-os/wiki/Known-Bugs-%28EN%29
- Format your title's issue as follow : 
- [Full Version][optional : KODI|ES|Buidroot|etc] short desc 

ex: [4.0.0-beta1][ES] keyboard dosbox doesn't work 

---
Please fill the following form :

### What happened
Press F4 and after try alt+f2 you end up locked at black screen.
### What should have happened
Opened root prompt
### Enumerate your devices
Raspbery pi 3 model b+
usb generic keyboard

**Comment by substring** [comment] 2017-04-22 07:23
Can't reproduce. Are tou sti facing this problem ?

**Comment by substring** [comment] 2017-10-14 13:09
no reply, closing

**Closed by substring** 2017-10-14 13:09 UTC
