### ISSUE TITLE
[KODI] Allow KODI to be updated separately

### ISSUE THREAD

**Issue by nate864** [recalbox/recalbox-os#1149] opened 2016-12-18 20:56 UTC
I'm completely new to the world of Recalbox and tried to find for an answer before posting, but I couldn't.
The closet idea was given in https://github.com/recalbox/recalbox-os/issues/429, but I acknowledge the advantages of a single-boot, so this is different.

Kodi v17 Krypton is about to be released and Recalbox is still on v15 Jarvis. Looking into yout buildroot files (not a programmer) I saw that 4.1 should come out with v16, though an outdated version. Kodi v17 has, of course, many improvements and I can't stop feeling a bit left behind. Kodi v15 works, no doubt, but it would be nicer to use a version not so far from "the state of the art".

I don't know if such feature would be possible without destroying the harmonious coexistence that you currently offer between Kodi and RecalboxOS, if you allow me to consider them as separate unities. But maybe it is something you also would like to have a this "issue" serves for showing interest.

Without further ado, I say goodbye with great appreciation and gratitude.

**Comment by substring** [comment] 2016-12-20 12:57
dupe of #1150

**Closed by substring** 2016-12-20 12:57 UTC
