### ISSUE TITLE
[4.0.2][ES]subfolders in systems

### ISSUE THREAD

**Issue by azvarel** [recalbox/recalbox-os#1202] opened 2017-02-24 19:06 UTC
I created the subfolders in systems snes example:
(1) Licensed
(2) Translated
(3) Unlicensed - Homebrew
(4) Pron
Non-Working

click the select button to enter option mode and choose jump to letter
choose any letter and clicking the action button,
it simply returns the screen in the "main snes" folder that contains:

(1) Licensed
(2) Translated
(3) Unlicensed - Homebrew
(4) Pron
Non-Working

more info https://forum.recalbox.com/topic/6592/subfolder-in-systems

**Comment by paradadf** [comment] 2017-02-24 19:31
This is a known bug. I'll try to find the already opened issue.

**Comment by azvarel** [comment] 2017-02-24 19:55
I did not find it, so I posted a new

**Comment by Voljega** [comment] 2017-02-24 20:05
Duplicate of https://github.com/recalbox/recalbox-os/issues/742

**Comment by rockaddicted** [comment] 2017-02-27 17:46
Hi, I close this issue.
Let's continue to talk about this problem in this issue #742

**Closed by rockaddicted** 2017-02-27 17:46 UTC
