### ISSUE TITLE
[4.0.2][ES] swithing to SEGA consoles lead to black screen

### ISSUE THREAD

**Issue by gege2b** [recalbox/recalbox-os#1230] opened 2017-03-10 09:13 UTC
Hi all, and thank you for this great software

I ran into a problem detailed below

### What happened
I selected one console (say, SNES for example) to show the list of games. Then, switching to the next console directly from here (i.e. without going back to main ES menu)

Going thru the console like this would cause  no problem, until - in my case - switching from Sega32x to the next console : I get a black screen.

I tried : 
- Moving away my ROMS from the Sega32x folder => Same problem but with the previous console on the list (Megadrive)
- Moving away Megadrive ROMS => idem, hangs when switching from Mastersystem ROMS
- Moving away Mastersystem ROMS ->  Problem was gone

So to say : moving away ALL my SEGA roms did the trick
So, it seems that SEGA consoles makes problem here.

I also logged as root and did the folowing : 

``` /etc/init.d/S31emulationstation restart ```

to show what happens and here are the results : 
```
lvl0:         Could not find <gameList> node in gamelist "/recalbox/share/roms/supergrafx/gamelist.xml"!
lvl0:   Could not find <gameList> node in gamelist "/recalbox/share/roms/vectrex/gamelist.xml"!
lvl0:   System "favorites" is missing name, path, extension, or command!
sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
 terminate called after throwing an instance of 'char const*' 
/etc/init.d/S31emulationstation: line 17:   674 Aborted                 HOME=/recalbox/share/system LC_ALL="fr_FR.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation
```
the script seems to hang at line 17, each time I ran into this problem

And here is the last 100 lines of recalbox.log (with all the ES restart in here)
```
[       13.08] : starting emulationstation with lang = fr_FR
[       13.10] : Starting emulationstation with command : 
[       13.11] : HOME=/recalbox/share/system LC_ALL="fr_FR.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation; [ -f /tmp/shutdown.please ] && (shutdown -h now);[ -f /tmp/reboot.please ] && (shutdown -r now)
---- recalbox-config.sh ----
udhcpc (v1.24.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, failing
---- recalbox-config.sh ----
[       31.26] : wlan0 be used as wifi interface
[       31.39] : starting wifi
udhcpc (v1.24.1) started
Sending discover...
Sending select for 192.168.1.223...
Lease of 192.168.1.223 obtained, lease time 86400
deleting routers
adding dns 192.168.1.1
          inet addr:192.168.1.223  Bcast:192.168.1.255  Mask:255.255.255.0
---- recalbox-config.sh ----
no update available
[       39.80] : Starting S92switch
[       39.82] : script /recalbox/scripts/powerswitch.sh [ STARTED ]
[       40.11] : Starting S94manager
Will not start pm2 : system.api.enabled is set to 0
[        8.37] : starting new log
[        8.39] : converting dos to unix carriage return characters
[        8.89] : setting audio to auto
[        8.90] : setting hostname to RECALBOX
[        8.91] : starting xarcade2jstick
---- recalbox-config.sh ----
[        8.95] : setting audio volume to 90
[        8.98] : setting audio output mode : auto
---- recalbox-config.sh ----
numid=3,iface=MIXER,name='PCM Playback Route'
  ; type=INTEGER,access=rw------,values=1,min=0,max=2,step=0
  : values=0
[        9.04] : setting audio volume : 90
Simple mixer control 'PCM',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback -663 [90%] [-6.63dB] [on]
[        9.07] : creating network entry in /var/lib/wpa_supplicant.conf
[        9.09] : setting keyboard layout to fr
[        9.10] : updated wifi settings : ssid=........ key=................................................
Loading /usr/share/keymaps/i386/azerty/fr.map.gz
[        9.30] : xarcade2jstick : no official stick found, looking for keyboard encoder now ...
[        9.60] : starting emulationstation with lang = fr_FR
[        9.62] : Starting emulationstation with command : 
[        9.63] : HOME=/recalbox/share/system LC_ALL="fr_FR.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation; [ -f /tmp/shutdown.please ] && (shutdown -h now);[ -f /tmp/reboot.please ] && (shutdown -r now)
---- recalbox-config.sh ----
udhcpc (v1.24.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, failing
---- recalbox-config.sh ----
[       25.56] : wlan0 be used as wifi interface
[       25.68] : starting wifi
udhcpc (v1.24.1) started
Sending discover...
Sending select for 192.168.1.223...
Lease of 192.168.1.223 obtained, lease time 86400
deleting routers
adding dns 192.168.1.1
          inet addr:192.168.1.223  Bcast:192.168.1.255  Mask:255.255.255.0
[       29.95] : Starting S92switch
[       29.96] : script /recalbox/scripts/powerswitch.sh [ STARTED ]
[       30.24] : Starting S94manager
Will not start pm2 : system.api.enabled is set to 0
---- recalbox-config.sh ----
no update available
[      152.76] : starting emulationstation with lang = fr_FR
[      152.77] : Starting emulationstation with command : 
[      152.79] : HOME=/recalbox/share/system LC_ALL="fr_FR.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation; [ -f /tmp/shutdown.please ] && (shutdown -h now);[ -f /tmp/reboot.please ] && (shutdown -r now)
lo IP Address 127.0.0.1
---- recalbox-config.sh ----
no update available
lo IP Address 127.0.0.1
wlan0 IP Address 192.168.1.223
[      315.54] : starting emulationstation with lang = fr_FR
[      315.56] : Starting emulationstation with command : 
[      315.57] : HOME=/recalbox/share/system LC_ALL="fr_FR.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation; [ -f /tmp/shutdown.please ] && (shutdown -h now);[ -f /tmp/reboot.please ] && (shutdown -r now)
---- recalbox-config.sh ----
no update available
lo IP Address 127.0.0.1
wlan0 IP Address 192.168.1.223
[      624.87] : starting emulationstation with lang = fr_FR
[      624.88] : Starting emulationstation with command : 
[      624.89] : HOME=/recalbox/share/system LC_ALL="fr_FR.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation; [ -f /tmp/shutdown.please ] && (shutdown -h now);[ -f /tmp/reboot.please ] && (shutdown -r now)
---- recalbox-config.sh ----
no update available
lo IP Address 127.0.0.1
wlan0 IP Address 192.168.1.223
[      887.58] : starting emulationstation with lang = fr_FR
[      887.59] : Starting emulationstation with command : 
[      887.60] : HOME=/recalbox/share/system LC_ALL="fr_FR.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation; [ -f /tmp/shutdown.please ] && (shutdown -h now);[ -f /tmp/reboot.please ] && (shutdown -r now)
---- recalbox-config.sh ----
no update available
```

### What should have happened
Switching to the next console without black screen

### Enumerate your devices
It's a home made bartop arcade box, with a computer monitor plugged using a HDMI-DVI cable
Controls : http://www.smallcab.net/joysticks-zippy-boutons-interface-p-387.html
(they say they're not compatible but I managed to make them work without problem)
Rpi3 with a 64GB class 10 SD
On this SD Card, I extracted some ROMS folder from the Picades 32GB image, and except some games, I can play to most of them

### How to reproduce the bug
In my case, it's always reproductible as long as I have a SEGA console available : 

- Enter into the SNES game list
- Switch to next console (using right arrow) until the black screen
- Voilà

Please, ask if you need some more informations
I'll try some more things and update this issue if I get more details

**Comment by rockaddicted** [comment] 2017-03-10 09:25
We don't provide support on github issues tracker.
So please use the forum and create a post.
First you have 2 corrupted gamelist.xml files.

```
lvl0:         Could not find <gameList> node in gamelist "/recalbox/share/roms/supergrafx/gamelist.xml"!
lvl0:   Could not find <gameList> node in gamelist "/recalbox/share/roms/vectrex/gamelist.xml"!
```

This problem is not from the system but from your gamelist.xml, scrape data. So clean them and retry.
If you need more support, I'll read you on the forum.

I close this issue.

**Closed by rockaddicted** 2017-03-10 09:25 UTC

**Comment by gege2b** [comment] 2017-03-10 13:58
Hi

Thank you for your answer but to be honest I don't ask for help.

I'm reporting what seems to be a bug. And I think I'm in the right place for this.

Anyway, I did what you suggest in your message, re-scrapping the problematic gamelist (indeed they was corrupt) and re-do the same test... And got the same problem.
As soon as I switch to a SEGA console, I run into this error.

```
# /etc/init.d/S31emulationstation start
# lvl0:         System "favorites" is missing name, path, extension, or command!
sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
terminate called after throwing an instance of 'char const*'
/etc/init.d/S31emulationstation: line 17:  1799 Aborted                 HOME=/recalbox/share/system LC_ALL="fr_FR.UTF-8" SDL_VIDEO_GL_DRIVER=/usr/lib/libGLESv2.so SDL_NOMOUSE=1 /usr/bin/emulationstation
```

**Comment by rockaddicted** [comment] 2017-03-10 14:10
I can't reproduce.
So what scraper are you using ?
Can you try scraped games ?

**Comment by gege2b** [comment] 2017-03-10 14:38
I did some more tests and I realized that I just need to enter in the Sega Mastersystem game list to trigger the crash

I deleted the gamelist.xml in the mastersystem, done a scrapping and this solved the issue
putting back the original xml make the issue reappeared

My guess is that something in the XML makes the system being mad and abort. So it's not specifically related to SEGA's game system

Anyway, the xml seems to be fine (i.e. not full of crappy chars), and there was nothing in the logs about that (except the "terminate called (...)" line shown above).

here is the [link to the problematic gamelist.xml](https://framadrop.org/r/5--nVESOKy#EYIkqb/mu958DFZu2csJfRldNxyWlIL4kolQbXF2EDM=) if you want to take a look at it

**Comment by gege2b** [comment] 2017-03-10 14:40
original gamelist.xml was extracted from http://picades.com/repository/#img "recalbox RPI3 32GB" disk image

**Comment by rockaddicted** [comment] 2017-03-10 14:43
no links with copyrighted contents

**Comment by gege2b** [comment] 2017-03-10 14:51
sorry, didn't think about that.
