### ISSUE TITLE
TP-Link TL-WN725N Driver missing

### ISSUE THREAD

**Issue by ghost** [recalbox/recalbox-os#93] opened 2015-03-04 09:41 UTC
Drivers can be found here: http://www.raspberrypi.org/forums/viewtopic.php?p=462982

**Comment by DanFaraday** [comment] 2015-03-04 12:00
Maybe this particular post could be useful: http://www.raspberrypi.org/forums/viewtopic.php?p=675971#p675971

**Comment by boopr** [comment] 2015-05-30 14:27
I agree, we need it.

**Comment by rockaddicted** [comment] 2015-10-06 19:43
wget https://github.com/lwfinger/rtl8188eu/raw/master/rtl8188eufw.bin -O /lib/firmware/rtlwifi/rtl8188eufw.bin

**Comment by digitalLumberjack** [comment] 2015-10-07 08:16
If that works, we add that directly in recalboxOS

**Comment by mxjoe** [comment] 2016-02-11 06:56
Hi Lumberjack, rockaddicted is right, that works and should be implemented in recalboxOS.
This issue is a duplicate of #230 .

**Comment by rockaddicted** [comment] 2016-02-11 07:12
firmware ok in recalbox 4.0.0
```
# ls -la /lib/firmware/rtlwifi/rtl8188eufw.bin 
-rw-r--r--    1 root     root         13904 Dec  7 03:17 /lib/firmware/rtlwifi/rtl8188eufw.bin
```

**Closed by rockaddicted** 2016-02-11 07:12 UTC
