### ISSUE TITLE
n64 locks up after a few minutes of use on all games (n64 and glide plugin)

### ISSUE THREAD

**Issue by SpiralingOut** [recalbox/recalbox-os#590] opened 2016-01-12 20:51 UTC
N64 was previously working (with a few tweaks) when I was running 3.2.11. I recently upgraded to beta 17 and now N64 locks up usually after 5 mins or so of use. This happens regardless of game.  I'm using an rpi2 and I've tried it overclocked and non-overclocked. I've tried n64 plugin and glide plugin and both have the same issue.

**Comment by fjen** [comment] 2016-01-13 18:38
I can confirm this issue for mario kart 64 at least.

**Comment by rockaddicted** [comment] 2016-01-13 18:55
Humm if the problem is not video plugin depends, maybe a problem with a mupen-rsp or mupen-core update.
I'll look that when I'll have a moment.

**Comment by paradadf** [comment] 2016-01-17 15:05
Hello! Do you have any news on this? I can confirm that every game is turning off and going back to the gamelists on beta 17.

**Comment by 5t4m** [comment] 2016-01-20 19:42
Same problem for me, but with recalbox v3.3.0-beta17 on an overclockd RPi2.
At first I thought this was a temperature problem and I bought a small CPU fan on top of the heatsinks.
![2016-01-20 20 23 56](https://cloud.githubusercontent.com/assets/16804978/12460549/7c68298c-bfb4-11e5-8cf9-f7c5da505b87.jpg)
However this didn't change a thing.

My Recalbox freezes after some time (1-30min) for n64 games, which need a lot of performance. So all games, which don't run 100% smoothly like Smash Bros. However, while the screen is frozen, I can still connect via SSH or Samba and copy/change files on the RPi.
For low-performance games like Diddy Kong Racing all seems fine.

Does someone have a clue or knows how to fix this?

**Comment by rockaddicted** [comment] 2016-01-21 08:41
Can you please try to switch audio plugin.
You must edit this file : `/recalbox/configs/mupen64/mupen64plus.cfg` 

then switch this line 
`AudioPlugin = "mupen64plus-audio-omx.so"` 
by this one 
`AudioPlugin = "mupen64plus-audio-sdl.so"`

I played 45min to super smash bross without any issue, and before N64 locks up always during the stage 2 "yoshi team world"
I'm using a rpi 2 overclocked.

I'm waiting your feedbacks.

**Comment by paradadf** [comment] 2016-01-21 17:19
With my overclocked rpi2, v.3.3.0 beta 17, gliden 64 and n64.videomode=default I still have the same problem :(. Mupen crashed after around 10 minutes with Mario Kart 64.

**Comment by rockaddicted** [comment] 2016-01-21 17:24
Are you on a crt screen ?
If not, don't use n64.videomode=default, but a video mode with a resolution max of 800x600 (DMT 1 or 9 - CEA 1).
Did you switch on SDL audio plugin ?

**Comment by paradadf** [comment] 2016-01-21 17:32
I changed the audio plugin to SDL, yes. I haven´t been able to make n64 work with a videomode other than default. But I will try again a report back here.

**Comment by rockaddicted** [comment] 2016-01-21 17:33
humm look this wiki : https://github.com/recalbox/recalbox-os/wiki/N64-%3A-return-to-ES-%28EN%29 (french version available too)

**Comment by paradadf** [comment] 2016-01-21 18:14
I have just tried with n64.videomode=DMT 4 HDMI (my only DMT mode available) and it crashed after around 10 minutes too.

**Comment by rockaddicted** [comment] 2016-01-21 18:33
Which game was you playing ?
I done 4 cups (16 worlds) in 50CC without any issues :-/

**Comment by paradadf** [comment] 2016-01-21 18:46
Mario Kart 64 in 150CC. It crashes everytime in the fourth world (Koopa Troopa Beach) in the first cup.

**Comment by rockaddicted** [comment] 2016-01-21 19:03
hummm I can't reproduce it... Just done the first cup in 150CC with Toad, and no problems.
Which character are you using ?
Are you using a special item when mupen locks up ? (star etc...)
Are you using oc preset included in recalbox or a custom one ?

Can you check on your TV that you are well in 600x480 resolution (info key on my tv command)

**Comment by paradadf** [comment] 2016-01-21 19:12
That´s weird :(
I was using Yoshi without items and the oc preset included in recalbox. My tv tells me 640x480 and 60Hz.

**Comment by SpiralingOut** [comment] 2016-01-21 19:18
I've tried multiple characters, single player, multiplayer, and multiplayer
battle mode and all lock up.  I tried using DMT 4 as well and had same
issue.

**Comment by rockaddicted** [comment] 2016-01-21 19:24
Did you switch your audio plugin @SpiralingOut ?

**Comment by SpiralingOut** [comment] 2016-01-21 19:30
Not yet.  I will try that tonight and report back.  So far my issue sounds
identical to @paradadf.

**Comment by substring** [comment] 2016-01-21 19:53
guyz, which version of the ROM are you using ? European one ? US ? Japanese ?

**Comment by paradadf** [comment] 2016-01-21 19:55
I`ve tried with both, EU and US version, and not only with Mario Kart.

**Comment by rockaddicted** [comment] 2016-01-21 20:43
@paradadf done the first cup in 150CC with yoshi, and no problems :-/
here is my setup : 
- roms no-intro : `12582912 Jul 10  2009 Mario Kart 64 (Europe) (Rev A).n64`
- plugin video : gliden64
- plugin audio : sdl
- video mode : DMT 4 HDMI
- overclocked using rpi2 preset in recalbox

**Comment by 5t4m** [comment] 2016-01-21 21:17
"then switch this line
AudioPlugin = "mupen64plus-audio-omx.so"
by this one
AudioPlugin = "mupen64plus-audio-sdl.so""
this got it working! thanks mate.
will do a bit more testing the next days

**Comment by paradadf** [comment] 2016-01-21 21:36
@rockaddicted on beta 17 or 4.0.0?
I think, I should just wait for the feedback from others and see if the problem is with my installation or not. Thank you for your effort!

**Comment by rockaddicted** [comment] 2016-01-21 21:42
I'm doing my n64 tests with a beta17 to be on the same setup than you.

**Comment by paradadf** [comment] 2016-01-22 23:50
I have very good news! I didn't know that pressing only the HOTKEY in n64 exits the emulator, as in every other you need the combination of HOTKEY+START. And I'm using a PS3 Controller (Shanwan), with the HOTKEY in L3. As n64 forces me to use the joystick to play, I suspected that somehow during the game L3 was gerting pressed (either by me or as a result of a cheap controller). So I changed the HOTKEY to the HOME button and played for around 20 minutes wirhout problems. Couldn't keep playing to test it more but it seems that changing the audio plugin solved the issue, and for me, changing the HOTKEY to the HOME button fixed my issue ;) 
I think the HOTKEY is actually assigned by default in PS3 Controllers to the HOME button, but I remapped it because it was recommended in the wiki. So, as long as there is no problem having the HOME button as HOTKEY, I will leave it there.

**Comment by paradadf** [comment] 2016-01-22 23:53
I just realized that, to my knowledge, remapping the buttons with ES shouldn't have any effect on Mupen. So I have no idea why it worked in my case :S

**Comment by digitalLumberjack** [comment] 2016-01-23 07:21
@paradadf it has effect on mupen (only the hotkey is configured)

**Comment by paradadf** [comment] 2016-01-23 11:14
That explains it then! Thanks!

**Comment by SpiralingOut** [comment] 2016-01-23 12:33
Changing audio plugin appears to have worked for me.   Thanks!

**Comment by rockaddicted** [comment] 2016-01-23 15:25
good news :smile: 
I close this issue.

**Comment by giefca** [comment] 2016-01-26 18:52
Changing audio plugin to sdl worked with gliden64 video plugin, no more crash after a few minutes of use but with rice video plugin I have a black screen with the game sound.  I tested 3 differents screen with all video mode. I switched back to the omx audio plugin and video came back. Maybe this 2 plugin are not compatible or there is an other parameter to change. I use recalbox 3.3.0 beta 17 on an overclocked rpi2.

**Comment by digitalLumberjack** [comment] 2016-01-26 20:01
Haha @rockaddicted n64 issues are never closed. They keep from the deep dark of github to haunt your night !

**Comment by rockaddicted** [comment] 2016-01-27 16:05
Haha indeed @digitalLumberjack. the best way to solve N64 issues, is to remove it from recalbox :wink: 
@giefca : Can you try to switch this setting in your `/recalbox/configs/mupen64/mupen64plus.cfg`
```
[Video-General]

# Use fullscreen mode if True, or windowed mode if False
Fullscreen = True
```
to
```
[Video-General]

# Use fullscreen mode if True, or windowed mode if False
Fullscreen = False
```
Then try again to start a game with `AudioPlugin = "mupen64plus-audio-sdl.so"` and `VideoPlugin = "mupen64plus-video-rice.so"`.

**Comment by giefca** [comment] 2016-01-27 17:31
Thanks! it worked, I'll try longer sessions to see if games don't freeze. 
recalbox can run a lot of n64 games without any problem it's would be a shame to remove it.

**Comment by rockaddicted** [comment] 2016-01-27 17:58
Haha nice
This time, I'll no more reopen it :wink:

**Closed by rockaddicted** 2016-01-27 17:58 UTC
