### ISSUE TITLE
[enhancement] Swap OK and Cancel button in Retroarch menus

### ISSUE THREAD

**Issue by Supernature2k** [recalbox/recalbox-os#1195] opened 2017-02-16 23:40 UTC
In ES we use B as OK and A as Cancel but the other way in Retroarch menus.

it would be more consistent to have the same layout in both.

it can be done by simply adding hereunder line in retroarchcustom.cfg:

`menu_swap_ok_cancel_buttons = "true"`

**Comment by paradadf** [comment] 2017-02-17 00:49
Duplicate of https://github.com/recalbox/recalbox-os/issues/624

**Comment by rockaddicted** [comment] 2017-02-17 04:27
I didn't added it because I wanted to add a switch US/JP in ES about control style.
But I won't do that the next weeks...

Can you please test and add it it in this file : `/recalbox/share_init/system/configs/retroarch/retroarchcustom.cfg.origin`

**Comment by substring** [comment] 2017-02-17 07:09
Already tested in #1175
@Supernature2k do as rockaddicted said

**Comment by Supernature2k** [comment] 2017-02-17 08:13
also tested, working as designed.

PR [#666](https://github.com/recalbox/recalbox-buildroot/pull/666) created

**Comment by substring** [comment] 2017-10-14 13:40
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0

**Closed by substring** 2017-10-14 13:40 UTC
