### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by MaxCorpEnjoy** [recalbox/recalbox-os#313] opened 2015-07-18 13:00 UTC
To refresh the game list, it is at the moment necessary to reboot the whole system.
Why not add a button somewhere, or better, refresh automatically the game list every X min or when we navigate throught the menu or when we exit a game ?

**Comment by Colmea** [comment] 2015-07-21 15:06
Duplicate of #293

**Closed** 2015-12-09 16:23 UTC
